# filebeat.yml - простая и рабочая конфигурация
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*-json.log'
    json.keys_under_root: true
    json.add_error_key: true

setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  index: 'logs-microservices-%{+yyyy.MM.dd}'
