filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true # Автоматически находит контейнеры

processors:
  # Добавляем Docker-метаданные (имя контейнера, образ и т.д.)
  - add_docker_metadata:
      host: 'unix:///var/run/docker.sock'

  # Пытаемся распарсить JSON, если логи в формате JSON
  - decode_json_fields:
      fields: ['message']
      target: 'json'
      overwrite_keys: true
      when:
        has_fields: ['message']

  # Добавляем поле с именем проекта для удобства фильтрации
  - add_fields:
      target: ''
      fields:
        project: 'microservices-course'

# Отключаем шаблоны индексов, так как управляем ими вручную/через Kibana
setup.ilm.enabled: false
setup.template.enabled: false

# Куда отправлять данные (в Elasticsearch)
output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  indices:
    - index: 'logs-microservices-%{+yyyy.MM.dd}'
